# Generated by Django 3.2.12 on 2022-02-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("authnapp", "0001_user_profile")]

    operations = []
